### ISSUE TITLE
Curvenote only loads plugins from the root project

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#538]
Given a folder structure like:

```
curvenote.yml
content/a/curvenote.yml
content/b/curvenote.yml
content/b/cool.mjs
```

and when running `curvenote` from the root folder, the plugin cool.mjs is not loaded. The only way to work with the plugin is to start curvenote in the `content/b/` folder and build that independently, which means you cannot build the whole site.

Can the plugin loading be extended to load all plugins from child projects?

**Comment by stevejpurves** [comment]
@fwkoch is this easy to do? we're using this structure on our docs site atm... or @rowanc1 could our docs site go down to 1 project? not sure what you have in mind for the multiple sub projects

**Comment by rowanc1** [comment]
I merged the projects into two yesterday, writing and publishing!

**Comment by stevejpurves** [comment]
~merged into two? do you mean split into two?~
~I see about 6 separate myst projects in the content folder, so if we are going that way this is still an issue~

Wrong branch! ok i see, yeah but it looks like we are sticking with 2 projects? (jeez we went all out on the multi-project stuff before)

**Comment by fwkoch** [comment]
I think this is addressed by: https://github.com/executablebooks/mystmd/pull/1119

The only thing to clarify - `content/a` and `content/b` must be explicitly added as projects to the root `site`. MyST will not arbitrarily traverse paths to find all config files on sub-directories.

**Comment by stevejpurves** [comment]
yep, tested out ok!

**Comment by fwkoch** [comment]
Fix is merged in myst, we can close this next time we update myst version here!
